### ISSUE TITLE
Searching for your Sonos System......

### ISSUE THREAD

**Issue by IsThisUserNameAvailable** [pascalopitz/unoffical-sonos-controller-for-linux#104]
I am trying to connect the controller to my Sonos play but it cannot find it.  I just see the Searching for oy  your Sonos System...' message.
I am running a Lenovo ideapad 330S-15ARR with Linux Mint 20 Ulyana base: Ubuntu 20.04 focal with PIA VPN (although I have disconnected the vpn to eliminate it from the equation).

If anyone has any suggestions I welcome them.

TIA
Nigel

**Comment by pascalopitz** [comment]
This might be due to your machine/network constellation not receiving multicasts correctly? Maybe some IP table settings?

I am working on a feature that will allow you to punch ion a known IP, if discovery fails.

See the discussion https://github.com/pascalopitz/unoffical-sonos-controller-for-linux/pull/102

**Comment by pascalopitz** [comment]
Ok, this is now included in https://github.com/pascalopitz/unoffical-sonos-controller-for-linux/releases/tag/v0.2.1-alpha7
