### ISSUE TITLE
Search not functional?

### ISSUE THREAD

**Issue by marcusklaas** [pascalopitz/unoffical-sonos-controller-for-linux#2]
First of all, thanks for making this plugin. It works very well, mostly. I'm having issues searching for things, though. No results are showing up...

I'm on Chrome 48 on a 64-bit Ubuntu machine.

**Comment by pascalopitz** [comment]
Hi there, can you shed some light on where your music is stored?
Did you install the app via the"install and run locally" section in the README? This should give you access to the chrome debugger, and you should be able to tell me some error codes  etc.

**Comment by marcusklaas** [comment]
I'm using Spotify. I haven't installed the app locally yet, simply pulled it from the Chrome app store. I could do the local thing tho.

**Comment by pascalopitz** [comment]
Ok, spotify is a 3rd party music service, and those are not yet working in my app, and maybe never will properly, due to the constraints of Sonos not letting you poach auth tokens easily.

You can try my "music services" branch, follow the instructions about installing locally, and let me know how you go. It requires  re-authing spotify  as a service for the player (i cannot get the auth token out of spotify), and might not work for all services, but spotify seemed to work.

This of course is WIP and not ready for the chrome store yet.
