### ISSUE TITLE
Java script error

### ISSUE THREAD

**Issue by jerikp** [pascalopitz/unoffical-sonos-controller-for-linux#202]
I get this error every time I close sonos controller. I'm running Zorin 17.1 Pro and I'm new to linux so not sure what to do

![Java script error](https://github.com/pascalopitz/unoffical-sonos-controller-for-linux/assets/141413174/198b4a72-debd-4bb5-8b88-6beccdc48fa0)

**Comment by jerikp** [comment]
Oh, I went back to Zorin 16.3 Pro and now I don't have the java error

**Comment by mjezewski** [comment]
The same error comes with latest Linux Mint OS so it seems not to be OS related

**Comment by jerikp** [comment]
That's not quite right, I'm currently using Linux Mint 21.3 right now and I haven't encountered the problem there yet

**Comment by mjezewski** [comment]
I am using the same Linux Mint 21.3 Virginia - this only points to the fact that the error is not OS related.

**Comment by lemanu38** [comment]
Hi everybody that Manuel from France, As the new sonos official controller is not working at all  since the latest upgrade, i've running now that unofficial version and i'm very happy to get music now. Congatulations for that very good job to Pascal. Buta couple of  days ago, i've made an update on the linux mint Kernel . And on my two PC. And now when i quite the application i've got the Java script Error ( exactly the same as described by Jerikp) also on both pc .  But after that i couldn't at all restart the app. Except if i remove the app , restart the pc and it's working fine until i quite again .
Is there anybody with a solution for that , i'm not a specialist of coding but familiar with terminal command and control. Many thanks

**Comment by lemanu38** [comment]
this is the error window i've got. i think the linux kernel update miss or remove something which is obviously necessary in the java lib?
![java script error](https://github.com/pascalopitz/unoffical-sonos-controller-for-linux/assets/114822492/1d24932c-6717-4665-bb13-a6b840383d14)

**Comment by lemanu38** [comment]
i'm also under mint 21.3 Virginia on both machines and i've just tried out the update of javascript to gir1.2-javascriptcoregtk-6.0 as mentioned  by mjezewski and issue still present. At each time i quit the app, i've got the error and to get it again running i must restart the pc.

**Comment by lemanu38** [comment]
So i 've a look to the PID number when the sonos App is running . ESRCH error i guess means the process ID hasn't been found to quite the app. i  'm waiting to see that with a ps -ef command on the terminal that' s right the sonos app is still running and it the reason i have to restart the pc to cancel it. by killing the process by kill {process ID}  the app could restard . But at this time i do not understand why the PID is not found. I' never works on Javascript . And there are no useful page on the web to found a solution by myself. Something is different in the environment since i've made the kernel upgrade. is there somebody who knows the missing part ???

**Comment by pascalopitz** [comment]
How did you guys all run the app? Have you tried out the AppImage, and is it the same with that?

**Comment by mjezewski** [comment]
Hi Pascal

I see the same problem

I have send you by mail my app state file.

The controller cannot start once again after closing and OS restart is needed.

Best regards

Michał
P.S. Maybe this one helps

https://stackoverflow.com/questions/47266005/unhandled-promise-rejection-rejection-id-1-error-kill-esrch

**Comment by mjezewski** [comment]
Removing .deb application and reinstalling it from the fresh downloaded package seems to heal the problem in my case.

**Comment by pascalopitz** [comment]
From now on I'll only publish AppImage

**Comment by pascalopitz** [comment]
Also I'll remove the local server functionality. This was very experimental I think the PID hanging is a symptom of the server process. There's been trouble with symlinks and indexing, and I'll chalk it up as a failed experiment.

**Comment by lemanu38** [comment]
Hi Pascal , i wasn't home this morning ,i will tried out to  remove the .deb application  and install it with the Appimage as soon as possible  and send you my report. Thanks for the support.

**Comment by mjezewski** [comment]
Thanks Pascal - I have downloaded your latest AppImage 0.4.0-rc1 and it is working without problems

**Comment by lemanu38** [comment]
Thanks Pascal , i've just download the AppImage 0.4.0-rc1 and running perfectly on my both machines. Since the official Sonos controller is bugged and last version doesn't work at all ,Now i 'm also searching for the equivalent of sonos controller unofficial but for Android. If i don not find i'll will begun a project to get it. Many thanks for you support and that good job.Manu

**Comment by mjezewski** [comment]
Hi Manu,
Indeed the new version of Sonos App is a disaster. You can find the old versions under https://www.apkmirror.com/uploads/?appcategory=sonos-for-android
Unfortunately, even if you check the updates out in the old App, the company is forcing update to the newest version and you would need to uninstall this one and install the old one (the best working was Sonos 16.1)
Sonos has promissed to release better versions with improved functionality but... when and how remains unclear.
Good Luck
Michal

**Comment by mjezewski** [comment]
User post relevant to the discussion above 
https://de.community.sonos.com/controller-und-musikdienste-223391/alte-app-wieder-installieren-so-gluecklich-6757481
M.

**Comment by lemanu38** [comment]
Many thanks mjezewski , i'll try to install on my phone as soon as possible. But really it's incredible that Sonos does't react at all on that subject. A lot of people surely in the next weeks, are going to replace ther sonos system with an new brand. In the latest weeks i also have a look to the comment on the sonos community forum , it' s a shame and a commercial nonsense. For Android i'm currently test and evaluate Hifi-cast-Musicplayer( free version on play store)

**Comment by mjezewski** [comment]
I have managed to make running the newest upgraded version of App - at least it has back the access to external library (but without setting and re-indexing it) and also the access to our radio stations (has required re-setting the myTuner Radio service.
For a moment minimum achieved but far from being satisfied...

**Comment by lemanu38** [comment]
Fom myself the original sonos app latest version doesn't work at all. when i start the app, its stays blocked on the advertising video with no button no possibility to go ahead.  And also after seeing the good behavior i have with alternative app, i guess the original sonos i completly de-preciated. I'm not interested as some people for timers and alrms features that have been cancelled on the last version i only wante de listen the music on my NAS and also some internet radios and services . I alway though the theme used in sonos app was poor, and some service doesn't display the album cover . i think sonos have really to create a very good app to make me coming back on their app.
