### ISSUE TITLE
Is it possible to restore debian packaging

### ISSUE THREAD

**Issue by camlafit** [pascalopitz/unoffical-sonos-controller-for-linux#207]
Hello

Is it possible to restore deb packaging ?
Maybe can I help about it

Thanks a lot

**Comment by adelolmo** [comment]
+1

**Comment by MDSvensson** [comment]
Absolutely a necessity. Please add it back! AppImage is just HELL to INSTALL. You don't, actually, and that is really bad:

1. Easy to loose track of what apps you "have".
2.  A set of 4+ instructions in order to create a proper launch icon that the system will detect. 

I understand that as a developer it is really cool to have a single file that you run and quickly iterate but as a user, it really really sucks. The snap version that does exist (btw snap also sucks) is stuck at version 0.30, which suffers from the services problem - adding a music service, take Plex for example, results in a  black screen and no functionality, rendering the entire app unusable for me. This issue is reported as a separate issue. The latest alpha fixed that but unfortunately it is available in the awful appimage format only.

**Comment by pascalopitz** [comment]
I'm not making any further changes to the repo

**Comment by MDSvensson** [comment]
I understand. By the way, thank you for the great work on this app. It is really great and mostly works well but do you know of any other apps, still actively maintained, that you would recommend to manage a home sonos speaker network? Thank you in advance!

**Comment by pascalopitz** [comment]
You can try Noson

**Comment by camlafit** [comment]
Hello

> I'm not making any further changes to the repo

sad news :/ 
Was/Is a very nice project. I hope you will come back later and continue with this project :)

> You can try Noson

https://github.com/janbar/noson-app/

Have a nice day
