### ISSUE TITLE
GPM no link when trying to add account

### ISSUE THREAD

**Issue by johanbroersma** [pascalopitz/unoffical-sonos-controller-for-linux#44]
Running version 0.1.0 on Ubuntu 16.04.

When trying to add a GPM account, and clicking "next" to create the authentication link no link appears. The instructions indicate a link is suppose to appear.

Thank you,
Johan

**Comment by pascalopitz** [comment]
Google have changed their smapi API and throw an error. it's not clear how
to fix it.

On 25 Aug. 2017 04:08, "johanbroersma" <notifications@github.com> wrote:

Running version 0.1.0 on Ubuntu 16.04.

When trying to add a GPM account, and clicking "next" to create the
authentication link no link appears. The instructions indicate a link is
suppose to appear.

Thank you,
Johan

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/pascalopitz/unoffical-sonos-controller-for-linux/issues/44>,
or mute the thread

**Comment by pascalopitz** [comment]
No solution on the horizon for this. Noson app also not working. I give up

**Comment by sfllaw** [comment]
@svrooij seems to have discovered a way to authenticate?
https://github.com/SoCo/SoCo/issues/586#issuecomment-728229811:
> @KennethNielsen I've [documented](https://svrooij.io/sonos-api-docs/music-services.html) how to connect to external music services.
> 
> anyone who wants me to continue this research, please [sponsor me](https://github.com/sponsors/svrooij?o=esc)
> 
> This file shows how to login to any music service [trigger login to music service](https://github.com/svrooij/node-sonos-ts/blob/beta/examples/music-services-login.js)
> 
> And this file shows how to browse any logged-in music service [browse](https://github.com/svrooij/node-sonos-ts/blob/beta/examples/music-services.js), I’ve tested Spotify and several others which are register for free.
> 
> The first link in this message shows what request to do, and the last two links show an actual working app querying music services. This information show be enough to replicate the same in python. Hope it helps... I also tried documenting the local Sonos api [here](https://svrooij.io/sonos-api-docs/services/) so if you want you can also use my work on that part to make SoCo even better.

**Comment by pascalopitz** [comment]
I have implemented hitting DeviceLink and AppLink as well. Just that Google is doing something different somehow ...
