### ISSUE TITLE
Music service issue(s) : Pocket Casts & Tunein

### ISSUE THREAD

**Issue by Avinguda21** [pascalopitz/unoffical-sonos-controller-for-linux#66]
Pocket Casts - service is added successfully BUT no contents are shown. 

Tunein - not available on menu or to add ???

**Comment by matt-from-uk** [comment]
Great work with this software - thanks so much

To follow up on what @Avinguda21 reported, if Tunein stations are saved already as Sonos Favourites they are available but if you click on the station it opens an empty list and does nothing - almost like opening an album but with no tracks.

Work around:
If you click on the arrow on the right and select play it works.

Expected behaviour:
If you click on a station it should play - not open a new (empty) list.

Sorry if this should be a new bug report but it is linked to Tunein not working directly

**Comment by pascalopitz** [comment]
Both services should now work, although searching TuneIn is broken, as there's a 404 on the PresentationMap which is linked at http://opml.radiotime.com/assets/sonos/map.xml

**Comment by pascalopitz** [comment]
Search fixed: https://github.com/pascalopitz/unoffical-sonos-controller-for-linux/commit/011ed59c980e54c696f476111f0e96c507ff939c
